# Use-case facade for notebook commands; delegates to notebook_data_manager.

from notebook.notebook_data_manager import (
    add_list_item,
    add_tags,
    append_to_entry_body,
    archive_entry,
    create_journal,
    create_list,
    create_note,
    get_entry,
    list_archived,
    list_by_group,
    list_by_tag,
    list_inbox,
    list_pinned,
    list_recent,
    pin_entry,
    remove_list_item,
    remove_tags,
    search_entries,
    set_entry_body,
    set_group,
    toggle_list_item_done,
)

__all__ = [
    "add_list_item",
    "add_tags",
    "append_to_entry_body",
    "archive_entry",
    "create_journal",
    "create_list",
    "create_note",
    "get_entry",
    "list_archived",
    "list_by_group",
    "list_by_tag",
    "list_inbox",
    "list_pinned",
    "list_recent",
    "pin_entry",
    "remove_list_item",
    "remove_tags",
    "search_entries",
    "set_entry_body",
    "set_group",
    "toggle_list_item_done",
]
