#!/usr/bin/env python3
# TOOL_TIER: supporting

"""Generate root .ruff.toml from shared development-tools exclusions."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Iterable, List

from development_tools.shared.standard_exclusions import (
    BASE_EXCLUSION_SHORTLIST,
    GENERATED_FILE_PATTERNS,
    get_exclusions,
)


_HEADER = (
    "# Auto-generated by development_tools/config/sync_ruff_toml.py\n"
    "# Source of truth: development_tools/shared/standard_exclusions.py +\n"
    "# development_tools/config/development_tools_config.json\n"
)


def _normalize_pattern(pattern: str) -> str:
    text = str(pattern or "").strip().replace("\\", "/")
    if not text:
        return ""
    # Placeholder pattern used by internal tools; not valid for Ruff.
    if "{domain}" in text:
        return ""
    return text.rstrip("/")


def _dedupe_preserve_order(values: Iterable[str]) -> List[str]:
    seen = set()
    result: List[str] = []
    for value in values:
        if not value or value in seen:
            continue
        seen.add(value)
        result.append(value)
    return result


def collect_ruff_exclusions() -> List[str]:
    raw_patterns: List[str] = []
    raw_patterns.extend(get_exclusions("analysis", "development"))
    raw_patterns.extend(BASE_EXCLUSION_SHORTLIST)
    raw_patterns.extend(GENERATED_FILE_PATTERNS)
    raw_patterns.append("ui/generated")
    normalized = [_normalize_pattern(pattern) for pattern in raw_patterns]
    exclusions = _dedupe_preserve_order(normalized)
    return sorted(exclusions)


def render_ruff_toml(exclusions: List[str]) -> str:
    quoted = ",\n".join(f'  "{value}"' for value in exclusions)
    return (
        f"{_HEADER}\n"
        "line-length = 88\n"
        'target-version = "py310"\n\n'
        "exclude = [\n"
        f"{quoted}\n"
        "]\n\n"
        "[lint]\n"
        'select = ["E", "F", "B", "UP", "SIM"]\n'
        'ignore = ["E501"]\n'
    )


def sync_ruff_toml(project_root: Path) -> Path:
    path = project_root / ".ruff.toml"
    content = render_ruff_toml(collect_ruff_exclusions())
    existing = ""
    if path.exists():
        existing = path.read_text(encoding="utf-8")
    if content != existing:
        path.write_text(content, encoding="utf-8")
    return path


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate root ruff.toml.")
    parser.add_argument(
        "--project-root",
        default=".",
        help="Project root where ruff.toml is written.",
    )
    args = parser.parse_args()
    project_root = Path(args.project_root).resolve()
    output_path = sync_ruff_toml(project_root)
    print(f"Generated {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
