#!/usr/bin/env python3
# TOOL_TIER: supporting

"""Generate root .ruff.toml from shared development-tools exclusions.

ruff.toml is fully generated: when development_tools_config.json is absent,
exclusions come only from standard_exclusions.py (non-project-specific).
When config exists, get_exclusions() may add project-specific patterns.
Run: python -m development_tools.config.sync_ruff_toml [--project-root .]
"""

from __future__ import annotations

import argparse
from pathlib import Path
from collections.abc import Iterable

from core.logger import get_component_logger
from development_tools.shared.standard_exclusions import (
    BASE_EXCLUSION_SHORTLIST,
    GENERATED_FILE_PATTERNS,
    get_exclusions,
)

logger = get_component_logger("development_tools")


_HEADER = (
    "# Auto-generated by development_tools/config/sync_ruff_toml.py\n"
    "# Source of truth: development_tools/shared/standard_exclusions.py +\n"
    "# development_tools/config/development_tools_config.json\n"
)


def _normalize_pattern(pattern: str) -> str:
    text = str(pattern or "").strip().replace("\\", "/")
    if not text:
        return ""
    # Placeholder pattern used by internal tools; not valid for Ruff.
    if "{domain}" in text:
        return ""
    return text.rstrip("/")


def _dedupe_preserve_order(values: Iterable[str]) -> list[str]:
    seen = set()
    result: list[str] = []
    for value in values:
        if not value or value in seen:
            continue
        seen.add(value)
        result.append(value)
    return result


def collect_ruff_exclusions() -> list[str]:
    raw_patterns: list[str] = []
    raw_patterns.extend(get_exclusions("analysis", "development"))
    raw_patterns.extend(BASE_EXCLUSION_SHORTLIST)
    raw_patterns.extend(GENERATED_FILE_PATTERNS)
    raw_patterns.append("ui/generated")
    normalized = [_normalize_pattern(pattern) for pattern in raw_patterns]
    exclusions = _dedupe_preserve_order(normalized)
    return sorted(exclusions)


def render_ruff_toml(exclusions: list[str]) -> str:
    quoted = ",\n".join(f'  "{value}"' for value in exclusions)
    return (
        f"{_HEADER}\n"
        "line-length = 88\n"
        'target-version = "py310"\n\n'
        "exclude = [\n"
        f"{quoted}\n"
        "]\n\n"
        "[lint]\n"
        'select = ["E", "F", "B", "UP", "SIM"]\n'
        'ignore = ["E501", "E402", "SIM117", "SIM102"]\n'
    )


def _resolve_config_path(project_root: Path, config_path: Path | str | None) -> Path:
    if config_path is None:
        return project_root / "development_tools" / "config" / "ruff.toml"
    path = Path(config_path)
    if path.is_absolute():
        return path
    return project_root / path


def _write_if_changed(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    existing = ""
    if path.exists():
        existing = path.read_text(encoding="utf-8")
    if content != existing:
        path.write_text(content, encoding="utf-8")


def sync_ruff_toml(
    project_root: Path,
    *,
    config_path: Path | str | None = None,
    sync_root_compat: bool = True,
) -> Path:
    owned_path = _resolve_config_path(project_root, config_path)
    content = render_ruff_toml(collect_ruff_exclusions())
    _write_if_changed(owned_path, content)
    if sync_root_compat:
        _write_if_changed(project_root / ".ruff.toml", content)
    return owned_path


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate root ruff.toml.")
    parser.add_argument(
        "--project-root",
        default=".",
        help="Project root where ruff.toml is written.",
    )
    parser.add_argument(
        "--config-path",
        default="development_tools/config/ruff.toml",
        help="Owned Ruff config path relative to project root (or absolute).",
    )
    parser.add_argument(
        "--no-root-compat",
        action="store_true",
        help="Do not generate compatibility .ruff.toml at repository root.",
    )
    args = parser.parse_args()
    project_root = Path(args.project_root).resolve()
    output_path = sync_ruff_toml(
        project_root,
        config_path=args.config_path,
        sync_root_compat=not args.no_root_compat,
    )
    if args.no_root_compat:
        logger.info("Wrote owned Ruff config: %s", output_path)
    else:
        logger.info(
            "Wrote owned Ruff config %s and root compatibility mirror %s",
            output_path,
            project_root / ".ruff.toml",
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
